import { LightningElement, api } from "lwc";
import { detailErrors, moveOptions } from "c/boardModel";

const FIELDS = ["title", "startDate", "dueDate"];

/**
 * One card, on either board. It renders the view model the board hands it - see
 * boardModel.cardModel - and decides nothing about the data.
 *
 * Both boards' cards expand in place, one at a time: the header is a disclosure button, the
 * board says which card is open through expandedKey, and Escape closes it again with focus back
 * on the header. What an open card can do beyond showing more is not the card's decision. The
 * internal board passes `abilities` - the statuses it can move to, whether it can edit, whether
 * the running user may open the record - and the public board passes nothing, so a public card
 * has one control, its disclosure, and no way to act.
 *
 * The card calls no Apex. It raises toggle, move, save and openrecord, and the board does the
 * work and hands the outcome back as `feedback`. That is what lets both boards share it: the
 * public bundle would carry any import this card made.
 *
 * No base components: this card runs in an LWR site, where every lightning-* component is one
 * more thing that can behave differently.
 */
export default class BoardCard extends LightningElement {
  @api card;
  /**
   * Internal board only: { moveTo: [status], edit, openRecord, retry, drag, titleMax }. Absent on
   * the public board, and every control below is absent with it. `drag` is true only while the
   * board has a fine pointer and is not in its portrait layout.
   */
  @api abilities;
  /** { key, url } for the record link, generated by the board for the open card. */
  @api recordLink;

  // Edits not yet saved, keyed by field, holding only what was touched.
  draft = {};
  // Problems the card found before sending anything.
  localErrors = {};
  // Fields edited since the server last reported on them; their server errors are stale.
  touched = new Set();
  isDragging = false;
  _expandedKey;
  _feedback;
  _dismissed;

  /** Which card on the board is open. This one is open when the key is its own. */
  @api
  get expandedKey() {
    return this._expandedKey;
  }
  set expandedKey(value) {
    const wasOpen = this.isExpanded;
    this._expandedKey = value;
    if (wasOpen !== this.isExpanded) {
      // Opening starts from what is saved; closing drops what was not.
      this.resetDraft();
    }
  }

  /**
   * What the board has to say about this card's last action: { key, busy, tone, message,
   * fieldErrors, saved }. A save that went through clears the draft, because what is saved is
   * now what the card shows.
   */
  @api
  get feedback() {
    return this._feedback;
  }
  set feedback(value) {
    this._feedback = value;
    this.touched = new Set();
    if (this.ownsFeedback && value.saved) {
      this.resetDraft();
    }
  }

  /** Puts focus on the header, for the board to call after a card has moved columns. */
  @api
  focusHeader() {
    const header = this.template.querySelector("[data-disclosure]");
    if (header) {
      header.focus();
    }
  }

  // ---------- state ----------

  get isExpanded() {
    return !!this.card && this._expandedKey === this.card.key;
  }
  get isCollapsed() {
    return !this.isExpanded;
  }
  get expandedText() {
    return String(this.isExpanded);
  }
  get cardClass() {
    const classes = ["card"];
    if (this.isExpanded) {
      classes.push("is-expanded");
    }
    if (this.isDragging) {
      classes.push("is-dragging");
    }
    // Saving a move or a retry: the card stays where it is until Salesforce has committed.
    if (this.isBusy) {
      classes.push("is-busy");
    }
    return classes.join(" ");
  }
  get headingClass() {
    return this.isExpanded
      ? `${this.card.headingClass} is-open`
      : this.card.headingClass;
  }
  /** The title and the sync chip, spoken with a pause between them. */
  get headerLabel() {
    return this.card.showSync
      ? `${this.card.heading}, ${this.card.syncStatus}`
      : this.card.heading;
  }
  get dateLine() {
    return this.isExpanded ? this.card.datesLong : this.card.dates;
  }
  get datesSpoken() {
    return this.isExpanded ? this.card.datesLongSpoken : this.card.datesSpoken;
  }
  get showParentNote() {
    return this.card.showParentNote && !this.isExpanded;
  }
  get hasFacts() {
    return !!(
      this.card.parentLine ||
      this.card.hasProjectLabel ||
      this.card.syncNote
    );
  }

  // ---------- abilities ----------

  get moveItems() {
    const moveTo = this.abilities && this.abilities.moveTo;
    return moveOptions(moveTo, this.card.status);
  }
  get hasMoveItems() {
    return this.moveItems.length > 0;
  }
  get canEdit() {
    return !!(this.abilities && this.abilities.edit);
  }
  get showRetry() {
    return !!(this.abilities && this.abilities.retry && this.card.isFailed);
  }
  /**
   * A drag starts from the card's detail lines, and only while it is closed. The header is a
   * button and an open card holds inputs; a drag never starts from either.
   */
  get canDrag() {
    return !!(this.abilities && this.abilities.drag) && !this.isExpanded;
  }
  get dragValue() {
    return this.canDrag ? "true" : null;
  }
  get showRecordLink() {
    return !!(
      this.abilities &&
      this.abilities.openRecord &&
      this.recordLink &&
      this.recordLink.key === this.card.key &&
      this.recordLink.url
    );
  }
  get recordUrl() {
    return this.showRecordLink ? this.recordLink.url : null;
  }
  get recordLinkLabel() {
    return `Open record ${this.card.recordNumber}`;
  }
  get showNoStartNote() {
    return !this.card.supportsStartDate;
  }
  /** A source that cannot hold a start date gets a sentence instead of an input. */
  get startUnsupportedNote() {
    return `${this.card.sourceLabel || "This source's"} items have no start date.`;
  }

  // ---------- feedback ----------

  get ownsFeedback() {
    return !!(
      this._feedback &&
      this.card &&
      this._feedback.key === this.card.key &&
      this._feedback !== this._dismissed
    );
  }
  get isBusy() {
    return this.ownsFeedback && !!this._feedback.busy;
  }
  get busyText() {
    return String(this.isBusy);
  }
  get feedbackMessage() {
    if (!this.ownsFeedback) {
      return "";
    }
    return this._feedback.busy ? "Saving…" : this._feedback.message || "";
  }
  get feedbackClass() {
    return this.ownsFeedback && this._feedback.tone === "error"
      ? "feedback feedback-error"
      : "feedback";
  }

  /** The server's field errors, less any field edited since, then the card's own. */
  get errors() {
    const server =
      (this.ownsFeedback && this._feedback.fieldErrors) || Object.create(null);
    const merged = {};
    FIELDS.forEach((field) => {
      const message =
        this.localErrors[field] ||
        (this.touched.has(field) ? null : server[field]);
      if (message) {
        merged[field] = message;
      }
    });
    return merged;
  }
  get titleError() {
    return this.errors.title || "";
  }
  get startError() {
    return this.errors.startDate || "";
  }
  get dueError() {
    return this.errors.dueDate || "";
  }
  get titleInvalid() {
    return String(!!this.errors.title);
  }
  get startInvalid() {
    return String(!!this.errors.startDate);
  }
  get dueInvalid() {
    return String(!!this.errors.dueDate);
  }

  // ---------- the draft ----------

  draftValue(field) {
    return field in this.draft ? this.draft[field] : this.card[field] || "";
  }
  get titleValue() {
    return this.draftValue("title");
  }
  get startValue() {
    return this.draftValue("startDate");
  }
  get dueValue() {
    return this.draftValue("dueDate");
  }

  resetDraft() {
    this.draft = {};
    this.localErrors = {};
    this.touched = new Set();
  }

  edit(field, value) {
    this.draft = { ...this.draft, [field]: value };
    const localErrors = { ...this.localErrors };
    delete localErrors[field];
    this.localErrors = localErrors;
    this.touched = new Set([...this.touched, field]);
  }

  // ---------- events ----------

  handleToggle() {
    this.dispatchEvent(
      new CustomEvent("toggle", { detail: { key: this.card.key } })
    );
  }

  /** Escape closes the open card from anywhere inside it and puts focus back on its header. */
  handleKeydown(event) {
    if (event.key === "Escape" && this.isExpanded) {
      event.stopPropagation();
      this.handleToggle();
      this.focusHeader();
    }
  }

  handleTitle(event) {
    this.edit("title", event.target.value);
  }
  handleStart(event) {
    this.edit("startDate", event.target.value);
  }
  handleDue(event) {
    this.edit("dueDate", event.target.value);
  }

  handleMove(event) {
    if (this.isBusy) {
      return;
    }
    this.dispatchEvent(
      new CustomEvent("move", {
        detail: { key: this.card.key, status: event.currentTarget.dataset.move }
      })
    );
  }

  /**
   * Checks the draft the way the server will, and sends it only when nothing is wrong. Dates
   * leave as the input's own YYYY-MM-DD strings, or empty for none.
   */
  handleSubmit(event) {
    event.preventDefault();
    if (this.isBusy) {
      return;
    }
    const values = {
      title: this.titleValue,
      startDate: this.card.supportsStartDate ? this.startValue : "",
      dueDate: this.dueValue
    };
    const found = detailErrors(values, {
      titleMax: this.abilities && this.abilities.titleMax,
      supportsStartDate: this.card.supportsStartDate,
      sourceLabel: this.card.sourceLabel
    });
    this.localErrors = found;
    const first = FIELDS.find((field) => found[field]);
    if (first) {
      const input = this.template.querySelector(`[data-field="${first}"]`);
      if (input) {
        input.focus();
      }
      return;
    }
    this.dispatchEvent(
      new CustomEvent("save", { detail: { key: this.card.key, ...values } })
    );
  }

  handleRetry() {
    if (this.isBusy) {
      return;
    }
    this.dispatchEvent(
      new CustomEvent("retry", { detail: { key: this.card.key } })
    );
  }

  /**
   * The drag carries the card's key, and the whole card is the image - not the two lines it was
   * picked up by. The board is told separately, because a drop target cannot read the data being
   * dragged until the drop.
   */
  handleDragStart(event) {
    if (!this.canDrag) {
      event.preventDefault();
      return;
    }
    const transfer = event.dataTransfer;
    if (transfer) {
      transfer.effectAllowed = "move";
      transfer.setData("application/x-work-item-key", this.card.key);
      const article = this.template.querySelector("article");
      if (article && transfer.setDragImage) {
        const box = article.getBoundingClientRect();
        transfer.setDragImage(
          article,
          event.clientX - box.left,
          event.clientY - box.top
        );
      }
    }
    this.isDragging = true;
    this.dispatchEvent(
      new CustomEvent("carddragstart", {
        detail: { key: this.card.key, status: this.card.status }
      })
    );
  }

  /** Dropped or abandoned: either way the card is back to rest. Nothing here opens or closes it. */
  handleDragEnd() {
    this.isDragging = false;
    this.dispatchEvent(
      new CustomEvent("carddragend", { detail: { key: this.card.key } })
    );
  }

  handleCancel() {
    this.resetDraft();
    this._dismissed = this._feedback;
  }

  /**
   * A plain click opens the record inside the app; a click with a modifier, or a middle click,
   * is left to the browser, so the link opens a new tab the way links do.
   */
  handleRecordLink(event) {
    if (
      event.button !== 0 ||
      event.metaKey ||
      event.ctrlKey ||
      event.shiftKey ||
      event.altKey
    ) {
      return;
    }
    event.preventDefault();
    this.dispatchEvent(
      new CustomEvent("openrecord", { detail: { key: this.card.key } })
    );
  }
}
