import { LightningElement, api } from "lwc";

/**
 * One epic card, on either board. It renders the view model the board hands it - see
 * boardModel.epicModel - and decides nothing about the data.
 *
 * It opens in place like every card, one at a time, to show the full title and where the epic
 * stands. It carries no editor on either board: an epic's progress is a rollup of its children,
 * and the children are where work is moved. It takes two abilities, both granted only by the
 * internal board: the record link, and since build 10 the button that features the epic on the
 * public board or removes it. Like every card it calls no Apex - the board does, on the feature
 * event, and hands the outcome back as feedback - so the public bundle imports nothing through it.
 *
 * Whether the epic is featured comes from the payload; the indicator's words come from the board.
 *
 * The progress bar is decorative and hidden from screen readers; the count beside it says the
 * same thing in words.
 */
export default class BoardEpicCard extends LightningElement {
  @api epic;
  /** Internal board only: { openRecord: Boolean, featureEpic: Boolean }. */
  @api abilities;
  /**
   * What the board has to say about this card's last action: { key, busy, tone, message }.
   * Build 10, for the feature button.
   */
  @api feedback;
  /** { key, url } for the record link, generated by the board for the open card. */
  @api recordLink;
  @api expandedKey;

  @api
  focusHeader() {
    const header = this.template.querySelector("[data-disclosure]");
    if (header) {
      header.focus();
    }
  }

  get isExpanded() {
    return !!this.epic && this.expandedKey === this.epic.key;
  }
  get isCollapsed() {
    return !this.isExpanded;
  }
  get expandedText() {
    return String(this.isExpanded);
  }
  get cardClass() {
    return this.isExpanded ? "card is-expanded" : "card";
  }
  get headingClass() {
    return this.isExpanded
      ? `${this.epic.headingClass} is-open`
      : this.epic.headingClass;
  }
  get showRecordLink() {
    return !!(
      this.abilities &&
      this.abilities.openRecord &&
      this.recordLink &&
      this.recordLink.key === this.epic.key &&
      this.recordLink.url
    );
  }
  get recordUrl() {
    return this.showRecordLink ? this.recordLink.url : null;
  }
  get recordLinkLabel() {
    return `Open record ${this.epic.recordNumber || ""}`.trim();
  }

  // ---------- the featured epic (build 10) ----------

  /** The header is described by the indicator, so a keyboard user hears it on reaching the card. */
  get featuredDescribedBy() {
    return this.epic && this.epic.showFeatured ? "featured" : null;
  }
  get showFeatureAction() {
    return !!(this.abilities && this.abilities.featureEpic);
  }
  get featureActionLabel() {
    return this.epic.isFeatured
      ? "Remove from public board"
      : "Feature on public board";
  }
  get ownsFeedback() {
    return !!(
      this.feedback &&
      this.epic &&
      this.feedback.key === this.epic.key
    );
  }
  get isBusy() {
    return this.ownsFeedback && !!this.feedback.busy;
  }
  get busyText() {
    return String(this.isBusy);
  }
  get feedbackMessage() {
    if (!this.ownsFeedback) {
      return "";
    }
    return this.feedback.busy ? "Saving…" : this.feedback.message || "";
  }
  get feedbackClass() {
    return this.ownsFeedback && this.feedback.tone === "error"
      ? "feedback feedback-error"
      : "feedback";
  }

  /** Asks the board to feature this epic, or to remove it when it is the featured one. */
  handleFeature() {
    if (this.isBusy) {
      return;
    }
    this.dispatchEvent(
      new CustomEvent("feature", {
        detail: { key: this.epic.key, feature: !this.epic.isFeatured }
      })
    );
  }

  handleToggle() {
    this.dispatchEvent(
      new CustomEvent("toggle", { detail: { key: this.epic.key } })
    );
  }

  handleKeydown(event) {
    if (event.key === "Escape" && this.isExpanded) {
      event.stopPropagation();
      this.handleToggle();
      this.focusHeader();
    }
  }

  handleRecordLink(event) {
    if (
      event.button !== 0 ||
      event.metaKey ||
      event.ctrlKey ||
      event.shiftKey ||
      event.altKey
    ) {
      return;
    }
    event.preventDefault();
    this.dispatchEvent(
      new CustomEvent("openrecord", { detail: { key: this.epic.key } })
    );
  }
}
