import { LightningElement, api } from "lwc";

/**
 * One epic card, on either board. It renders the view model the board hands it - see
 * boardModel.epicModel - and decides nothing about the data.
 *
 * It opens in place like every card, one at a time, to show the full title and where the epic
 * stands. It carries no editor on either board: an epic's progress is a rollup of its children,
 * and the children are where work is moved. The one ability it takes is the record link, which
 * only the internal board grants.
 *
 * The progress bar is decorative and hidden from screen readers; the count beside it says the
 * same thing in words.
 */
export default class BoardEpicCard extends LightningElement {
  @api epic;
  /** Internal board only: { openRecord: Boolean }. */
  @api abilities;
  /** { key, url } for the record link, generated by the board for the open card. */
  @api recordLink;
  @api expandedKey;

  @api
  focusHeader() {
    const header = this.template.querySelector("[data-disclosure]");
    if (header) {
      header.focus();
    }
  }

  get isExpanded() {
    return !!this.epic && this.expandedKey === this.epic.key;
  }
  get isCollapsed() {
    return !this.isExpanded;
  }
  get expandedText() {
    return String(this.isExpanded);
  }
  get cardClass() {
    return this.isExpanded ? "card is-expanded" : "card";
  }
  get headingClass() {
    return this.isExpanded
      ? `${this.epic.headingClass} is-open`
      : this.epic.headingClass;
  }
  get showRecordLink() {
    return !!(
      this.abilities &&
      this.abilities.openRecord &&
      this.recordLink &&
      this.recordLink.key === this.epic.key &&
      this.recordLink.url
    );
  }
  get recordUrl() {
    return this.showRecordLink ? this.recordLink.url : null;
  }
  get recordLinkLabel() {
    return `Open record ${this.epic.recordNumber || ""}`.trim();
  }

  handleToggle() {
    this.dispatchEvent(
      new CustomEvent("toggle", { detail: { key: this.epic.key } })
    );
  }

  handleKeydown(event) {
    if (event.key === "Escape" && this.isExpanded) {
      event.stopPropagation();
      this.handleToggle();
      this.focusHeader();
    }
  }

  handleRecordLink(event) {
    if (
      event.button !== 0 ||
      event.metaKey ||
      event.ctrlKey ||
      event.shiftKey ||
      event.altKey
    ) {
      return;
    }
    event.preventDefault();
    this.dispatchEvent(
      new CustomEvent("openrecord", { detail: { key: this.epic.key } })
    );
  }
}
